### ISSUE TITLE
How to use invoice subscriptions?

### ISSUE THREAD

**Issue by ramontayag** [RooSoft/lnd_client#8]
This is where my lack of Elixir knowledge shows, and it's not necessarily lnd_client specific, but after 30 mins of Googling I have not found the answer.

How do you tap into `LndClient.Tools.InvoiceUpdates`? I see that when I pay an invoice created using #6, the invoice is printed on the console.

What I imagine is running a function, defined in my app, with the invoice struct as an arg so I can do something about it in my app (i.e. update the database that the invoice has been paid and ping a webhook url).

**Comment by RooSoft** [comment]
This lib could use some little overhaul, as it's probably the first one I did in Elixir a little while ago.

The [InvoiceUpdates](https://github.com/RooSoft/lnd_client/blob/cca20890e5d1bee4223ec3bf6daf778eab92dea2/lib/tools/invoice_updates.ex) is a GenServer that's started directly from the `.iex.exs` file in the root folder. This means, if you start iex, it will start automatically.

What it does, is call `LndClient.subscribe_invoices` with its own GenServer process pid. It then expects to get some messages, and that's the reason why it has `handle_info` functions. These are the ones printing what you see in the console.

Now... this module is pretty much useless in a standalone app that's using `lnd_client`. But... that specific app can use the `LndClient.Tools.InvoiceUpdates` module as a blueprint to create its own and manage invoices however it's supposed to.

Does it make sense?

**Comment by RooSoft** [comment]
Also, I am figuring out that `lnd_client` is not configured yet to be published in hex, so, I will make sure do correct this soon.

From that point on, you'll just have to use it as a dependency, get it from the cloud with `mix deps.get` and do the above so you can act on invoice messages from LND.

**Comment by ramontayag** [comment]
> This lib could use some little overhaul, as it's probably the first one I did in Elixir a little while ago.
> 
> The [InvoiceUpdates](https://github.com/RooSoft/lnd_client/blob/cca20890e5d1bee4223ec3bf6daf778eab92dea2/lib/tools/invoice_updates.ex) is a GenServer that's started directly from the `.iex.exs` file in the root folder. This means, if you start iex, it will start automatically.
> 
> What it does, is call `LndClient.subscribe_invoices` with its own GenServer process pid. It then expects to get some messages, and that's the reason why it has `handle_info` functions. These are the ones printing what you see in the console.
> 
> Now... this module is pretty much useless in a standalone app that's using `lnd_client`. But... that specific app can use the `LndClient.Tools.InvoiceUpdates` module as a blueprint to create its own and manage invoices however it's supposed to.
> 
> Does it make sense?

Oh I see. My web app will make its own gen server to get updates. Got it! I thought there was some way to just plug into that gen server (updating it of course)

**Comment by RooSoft** [comment]
Well, the quickest way to consume this data is to subscribe and create a `handle_info` function straight in a LiveView page.

I don't necessarily recommend it, cause every page viewer will get its own subscription instead of having one for the whole site.. but it would work without having to code your own GenServer and would be an easy way to test this lib and have instant visuals.
